/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StyleguideRouteImport } from './routes/styleguide'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlanERouteImport } from './routes/plan.e'
import { Route as PlanDRouteImport } from './routes/plan.d'
import { Route as PlanCRouteImport } from './routes/plan.c'
import { Route as PlanBRouteImport } from './routes/plan.b'
import { Route as PlanARouteImport } from './routes/plan.a'
import { Route as OnboardingBridgeRouteImport } from './routes/onboarding/bridge'
import { Route as ApiJadeObjectRouteImport } from './routes/api/jade/object'
import { Route as ApiJadeHelloRouteImport } from './routes/api/jade/hello'
import { Route as ApiJadeChatRouteImport } from './routes/api/jade/chat'
import { Route as ApiClerkWebhookRouteImport } from './routes/api/clerk.webhook'

const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanERoute = PlanERouteImport.update({
  id: '/plan/e',
  path: '/plan/e',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanDRoute = PlanDRouteImport.update({
  id: '/plan/d',
  path: '/plan/d',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanCRoute = PlanCRouteImport.update({
  id: '/plan/c',
  path: '/plan/c',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanBRoute = PlanBRouteImport.update({
  id: '/plan/b',
  path: '/plan/b',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanARoute = PlanARouteImport.update({
  id: '/plan/a',
  path: '/plan/a',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingBridgeRoute = OnboardingBridgeRouteImport.update({
  id: '/onboarding/bridge',
  path: '/onboarding/bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJadeObjectRoute = ApiJadeObjectRouteImport.update({
  id: '/api/jade/object',
  path: '/api/jade/object',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJadeHelloRoute = ApiJadeHelloRouteImport.update({
  id: '/api/jade/hello',
  path: '/api/jade/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJadeChatRoute = ApiJadeChatRouteImport.update({
  id: '/api/jade/chat',
  path: '/api/jade/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClerkWebhookRoute = ApiClerkWebhookRouteImport.update({
  id: '/api/clerk/webhook',
  path: '/api/clerk/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/styleguide': typeof StyleguideRoute
  '/onboarding/bridge': typeof OnboardingBridgeRoute
  '/plan/a': typeof PlanARoute
  '/plan/b': typeof PlanBRoute
  '/plan/c': typeof PlanCRoute
  '/plan/d': typeof PlanDRoute
  '/plan/e': typeof PlanERoute
  '/api/clerk/webhook': typeof ApiClerkWebhookRoute
  '/api/jade/chat': typeof ApiJadeChatRoute
  '/api/jade/hello': typeof ApiJadeHelloRoute
  '/api/jade/object': typeof ApiJadeObjectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/styleguide': typeof StyleguideRoute
  '/onboarding/bridge': typeof OnboardingBridgeRoute
  '/plan/a': typeof PlanARoute
  '/plan/b': typeof PlanBRoute
  '/plan/c': typeof PlanCRoute
  '/plan/d': typeof PlanDRoute
  '/plan/e': typeof PlanERoute
  '/api/clerk/webhook': typeof ApiClerkWebhookRoute
  '/api/jade/chat': typeof ApiJadeChatRoute
  '/api/jade/hello': typeof ApiJadeHelloRoute
  '/api/jade/object': typeof ApiJadeObjectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/styleguide': typeof StyleguideRoute
  '/onboarding/bridge': typeof OnboardingBridgeRoute
  '/plan/a': typeof PlanARoute
  '/plan/b': typeof PlanBRoute
  '/plan/c': typeof PlanCRoute
  '/plan/d': typeof PlanDRoute
  '/plan/e': typeof PlanERoute
  '/api/clerk/webhook': typeof ApiClerkWebhookRoute
  '/api/jade/chat': typeof ApiJadeChatRoute
  '/api/jade/hello': typeof ApiJadeHelloRoute
  '/api/jade/object': typeof ApiJadeObjectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/styleguide'
    | '/onboarding/bridge'
    | '/plan/a'
    | '/plan/b'
    | '/plan/c'
    | '/plan/d'
    | '/plan/e'
    | '/api/clerk/webhook'
    | '/api/jade/chat'
    | '/api/jade/hello'
    | '/api/jade/object'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/styleguide'
    | '/onboarding/bridge'
    | '/plan/a'
    | '/plan/b'
    | '/plan/c'
    | '/plan/d'
    | '/plan/e'
    | '/api/clerk/webhook'
    | '/api/jade/chat'
    | '/api/jade/hello'
    | '/api/jade/object'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/styleguide'
    | '/onboarding/bridge'
    | '/plan/a'
    | '/plan/b'
    | '/plan/c'
    | '/plan/d'
    | '/plan/e'
    | '/api/clerk/webhook'
    | '/api/jade/chat'
    | '/api/jade/hello'
    | '/api/jade/object'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  StyleguideRoute: typeof StyleguideRoute
  OnboardingBridgeRoute: typeof OnboardingBridgeRoute
  PlanARoute: typeof PlanARoute
  PlanBRoute: typeof PlanBRoute
  PlanCRoute: typeof PlanCRoute
  PlanDRoute: typeof PlanDRoute
  PlanERoute: typeof PlanERoute
  ApiClerkWebhookRoute: typeof ApiClerkWebhookRoute
  ApiJadeChatRoute: typeof ApiJadeChatRoute
  ApiJadeHelloRoute: typeof ApiJadeHelloRoute
  ApiJadeObjectRoute: typeof ApiJadeObjectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/e': {
      id: '/plan/e'
      path: '/plan/e'
      fullPath: '/plan/e'
      preLoaderRoute: typeof PlanERouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/d': {
      id: '/plan/d'
      path: '/plan/d'
      fullPath: '/plan/d'
      preLoaderRoute: typeof PlanDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/c': {
      id: '/plan/c'
      path: '/plan/c'
      fullPath: '/plan/c'
      preLoaderRoute: typeof PlanCRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/b': {
      id: '/plan/b'
      path: '/plan/b'
      fullPath: '/plan/b'
      preLoaderRoute: typeof PlanBRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/a': {
      id: '/plan/a'
      path: '/plan/a'
      fullPath: '/plan/a'
      preLoaderRoute: typeof PlanARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/bridge': {
      id: '/onboarding/bridge'
      path: '/onboarding/bridge'
      fullPath: '/onboarding/bridge'
      preLoaderRoute: typeof OnboardingBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jade/object': {
      id: '/api/jade/object'
      path: '/api/jade/object'
      fullPath: '/api/jade/object'
      preLoaderRoute: typeof ApiJadeObjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jade/hello': {
      id: '/api/jade/hello'
      path: '/api/jade/hello'
      fullPath: '/api/jade/hello'
      preLoaderRoute: typeof ApiJadeHelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jade/chat': {
      id: '/api/jade/chat'
      path: '/api/jade/chat'
      fullPath: '/api/jade/chat'
      preLoaderRoute: typeof ApiJadeChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clerk/webhook': {
      id: '/api/clerk/webhook'
      path: '/api/clerk/webhook'
      fullPath: '/api/clerk/webhook'
      preLoaderRoute: typeof ApiClerkWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  StyleguideRoute: StyleguideRoute,
  OnboardingBridgeRoute: OnboardingBridgeRoute,
  PlanARoute: PlanARoute,
  PlanBRoute: PlanBRoute,
  PlanCRoute: PlanCRoute,
  PlanDRoute: PlanDRoute,
  PlanERoute: PlanERoute,
  ApiClerkWebhookRoute: ApiClerkWebhookRoute,
  ApiJadeChatRoute: ApiJadeChatRoute,
  ApiJadeHelloRoute: ApiJadeHelloRoute,
  ApiJadeObjectRoute: ApiJadeObjectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
