/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YouRouteImport } from './routes/you'
import { Route as StyleguideRouteImport } from './routes/styleguide'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as CookbookRouteImport } from './routes/cookbook'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlanARouteImport } from './routes/plan.a'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const YouRoute = YouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const CookbookRoute = CookbookRouteImport.update({
  id: '/cookbook',
  path: '/cookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanARoute = PlanARouteImport.update({
  id: '/plan/a',
  path: '/plan/a',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookbook': typeof CookbookRoute
  '/shopping': typeof ShoppingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/styleguide': typeof StyleguideRoute
  '/you': typeof YouRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/plan/a': typeof PlanARoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookbook': typeof CookbookRoute
  '/shopping': typeof ShoppingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/styleguide': typeof StyleguideRoute
  '/you': typeof YouRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/plan/a': typeof PlanARoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookbook': typeof CookbookRoute
  '/shopping': typeof ShoppingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/styleguide': typeof StyleguideRoute
  '/you': typeof YouRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/plan/a': typeof PlanARoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookbook'
    | '/shopping'
    | '/sign-in'
    | '/sign-up'
    | '/styleguide'
    | '/you'
    | '/auth/callback'
    | '/plan/a'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookbook'
    | '/shopping'
    | '/sign-in'
    | '/sign-up'
    | '/styleguide'
    | '/you'
    | '/auth/callback'
    | '/plan/a'
  id:
    | '__root__'
    | '/'
    | '/cookbook'
    | '/shopping'
    | '/sign-in'
    | '/sign-up'
    | '/styleguide'
    | '/you'
    | '/auth/callback'
    | '/plan/a'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookbookRoute: typeof CookbookRoute
  ShoppingRoute: typeof ShoppingRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  StyleguideRoute: typeof StyleguideRoute
  YouRoute: typeof YouRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PlanARoute: typeof PlanARoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/you': {
      id: '/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof YouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookbook': {
      id: '/cookbook'
      path: '/cookbook'
      fullPath: '/cookbook'
      preLoaderRoute: typeof CookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/a': {
      id: '/plan/a'
      path: '/plan/a'
      fullPath: '/plan/a'
      preLoaderRoute: typeof PlanARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookbookRoute: CookbookRoute,
  ShoppingRoute: ShoppingRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  StyleguideRoute: StyleguideRoute,
  YouRoute: YouRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PlanARoute: PlanARoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
