/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YouRouteImport } from './routes/you'
import { Route as StyleguideRouteImport } from './routes/styleguide'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CookbookRouteImport } from './routes/cookbook'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlanARouteImport } from './routes/plan.a'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiJadeObjectRouteImport } from './routes/api/jade/object'
import { Route as ApiJadeHelloRouteImport } from './routes/api/jade/hello'

const YouRoute = YouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CookbookRoute = CookbookRouteImport.update({
  id: '/cookbook',
  path: '/cookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanARoute = PlanARouteImport.update({
  id: '/plan/a',
  path: '/plan/a',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJadeObjectRoute = ApiJadeObjectRouteImport.update({
  id: '/api/jade/object',
  path: '/api/jade/object',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJadeHelloRoute = ApiJadeHelloRouteImport.update({
  id: '/api/jade/hello',
  path: '/api/jade/hello',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookbook': typeof CookbookRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/styleguide': typeof StyleguideRoute
  '/you': typeof YouRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/plan/a': typeof PlanARoute
  '/api/jade/hello': typeof ApiJadeHelloRoute
  '/api/jade/object': typeof ApiJadeObjectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookbook': typeof CookbookRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/styleguide': typeof StyleguideRoute
  '/you': typeof YouRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/plan/a': typeof PlanARoute
  '/api/jade/hello': typeof ApiJadeHelloRoute
  '/api/jade/object': typeof ApiJadeObjectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookbook': typeof CookbookRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/styleguide': typeof StyleguideRoute
  '/you': typeof YouRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/plan/a': typeof PlanARoute
  '/api/jade/hello': typeof ApiJadeHelloRoute
  '/api/jade/object': typeof ApiJadeObjectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookbook'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/styleguide'
    | '/you'
    | '/auth/callback'
    | '/plan/a'
    | '/api/jade/hello'
    | '/api/jade/object'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookbook'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/styleguide'
    | '/you'
    | '/auth/callback'
    | '/plan/a'
    | '/api/jade/hello'
    | '/api/jade/object'
  id:
    | '__root__'
    | '/'
    | '/cookbook'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/styleguide'
    | '/you'
    | '/auth/callback'
    | '/plan/a'
    | '/api/jade/hello'
    | '/api/jade/object'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookbookRoute: typeof CookbookRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  StyleguideRoute: typeof StyleguideRoute
  YouRoute: typeof YouRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PlanARoute: typeof PlanARoute
  ApiJadeHelloRoute: typeof ApiJadeHelloRoute
  ApiJadeObjectRoute: typeof ApiJadeObjectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/you': {
      id: '/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof YouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookbook': {
      id: '/cookbook'
      path: '/cookbook'
      fullPath: '/cookbook'
      preLoaderRoute: typeof CookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/a': {
      id: '/plan/a'
      path: '/plan/a'
      fullPath: '/plan/a'
      preLoaderRoute: typeof PlanARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jade/object': {
      id: '/api/jade/object'
      path: '/api/jade/object'
      fullPath: '/api/jade/object'
      preLoaderRoute: typeof ApiJadeObjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jade/hello': {
      id: '/api/jade/hello'
      path: '/api/jade/hello'
      fullPath: '/api/jade/hello'
      preLoaderRoute: typeof ApiJadeHelloRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookbookRoute: CookbookRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  StyleguideRoute: StyleguideRoute,
  YouRoute: YouRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PlanARoute: PlanARoute,
  ApiJadeHelloRoute: ApiJadeHelloRoute,
  ApiJadeObjectRoute: ApiJadeObjectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
