import { createFileRoute } from "@tanstack/react-router";
import { listConversations, latestConversationId, conversationMessages, createConversation, generateOpener } from "@/server/vana/chat";
import { currentUserId } from "@/server/vana/auth";
import { RateLimitedError } from "@/server/vana/rate-limit";
import type { ConversationKind } from "@/lib/vana/contracts";

const kindOf = (v: string | null | undefined): ConversationKind => (v === "general" ? "general" : "meal_planning");
/** GET ?kind= → { conversations } · GET ?id=<id|latest>&kind= → { id, kind, messages } · POST { kind } → creates (or reuses a <24h untouched one) + Vana's opener → { id, kind, messages }. */
export const Route = createFileRoute("/api/vana/conversations")({
  server: {
    handlers: {
      GET: async ({ request }) => {
        const userId = await currentUserId();
        if (!userId) return Response.json({ error: "unauthenticated" }, { status: 401 });
        const u = new URL(request.url); const id = u.searchParams.get("id"); const kind = kindOf(u.searchParams.get("kind"));
        try {
          if (!id) return Response.json({ conversations: await listConversations(userId, 40, u.searchParams.get("kind") ? kind : undefined) });
          const cid = id === "latest" ? await latestConversationId(userId, kind) : id;
          if (!cid) return Response.json({ id: null, kind, messages: [] });
          const r = await conversationMessages(userId, cid);
          return Response.json({ id: cid, kind: r.kind, messages: r.messages });
        } catch (e) { return Response.json({ error: (e as Error).message }, { status: 500 }); }
      },
      POST: async ({ request }) => {
        const userId = await currentUserId();
        if (!userId) return Response.json({ error: "unauthenticated" }, { status: 401 });
        const body = (await request.json().catch(() => ({}))) as { kind?: string };
        const kind = kindOf(body.kind);
        try {
          // Always fresh: reusing a <24h untouched opener replays one generated by an older prompt.
          const id = await createConversation(userId, kind); const messages = kind === "general" ? [] : await generateOpener(userId, id, kind); return Response.json({ id, kind, messages });
        } catch (e) {
          if (e instanceof RateLimitedError) return Response.json({ error: "rate_limited", retry_after_seconds: e.retryAfterSeconds, retryAfterSeconds: e.retryAfterSeconds }, { status: 429 });
          return Response.json({ error: (e as Error).message }, { status: 500 });
        }
      },
    },
  },
});
